name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d --build

    - name: push image to docker hub
      run: docker push umair096/testdeployment:tagname
    - name: Login to Docker Hub
      run: docker login -u ${{ umair096 }} -p ${{ D0ck3r81301--}}

    - name: Push image to Docker Hub
      run: docker push umair096/testdeployment:tagname

    - name: Logout from Docker Hub
      run: docker logout
